### ISSUE TITLE
Make development setup easier

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-security-system#11]
Currently setting up a development environment is a pain due to there being no clear way to generate auth tokens for the API.

I think(?) theres a function in `Auth_plug` that can generate Auth tokens client side, we should see if we can add this to a Mix command

+ [ ] Add a command to generate an Auth token automatically for development

**Comment by t0mhaines** [comment]
*Making development setup easier* is a very broad term, here are a few ideas that could help:

+ **Documentation**: We can increase documentation and add some helper commands to make creating and developing auth keys easier but still require manually obtaining and starting the development servers.

+ **Docker**: Try for a *1 click install* by running `docker-compose up`. This can have an added benefit of a controlled development environment but will require a large amount of upfront cost.

+ **Scripts**: Try for a *1 click install* using shell/python(?) scripts that will pull and set everything up. These may not always work (e.g. Linux/Mac/Windows) differences but will be a lot lighter to run/less dependencies

@nelsonic thoughts?

**Comment by nelsonic** [comment]
@th0mas Yeah, creating Auth API Keys is not going to be easier. 
We've got it down to a _single_ environment variable. 
(_unless you can think of a way to automate it...?_)

Please note: the UI for Auth API Key creation is going to change shortly due to the creation of "Apps" https://github.com/dwyl/auth/issues/95
But it will be the same number of steps and single environment variable. I will update the screenshots/steps in my PR.

As for using **Docker**, unless we are _deploying_ using docker (_and don't have any other choice_),
I would prefer to avoid it because it's another thing to have to maintain/update. 
While we have a precedent for using Docker see: https://github.com/dwyl/learn-docker#docker-and-pete-stack  
@SimonLab  is using it to run Postgres on his machine: https://github.com/dwyl/learn-docker/issues/15#issuecomment-606641149
I'd prefer to attempt the (_well commented/documented_) **`Python`** approach if possible,
but it depends on your estimate for how long you think it will take.

Not at all concerned about this working on Windows. In fact I would add "**Microsoft Windows _Not Supported_**" to the `README.md` to avoid any issues from people attempting to run it. We will [_never_ use Windows for anything secure](https://krebsonsecurity.com/2020/08/microsoft-put-off-fixing-zero-day-for-2-years/). 💔
