### ISSUE TITLE
Controlling an electric strike from RPi w/ PoE

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-security-system#14]
Currently, I have been able to connect up a RPi and the NFC development board using PoE and a USB-C splitter. I've found no issues with this. 

PoE is 48V which is *far* too high to power our 12v door strikes.  We need to work out a way to step down the power to 12v, and, if possible, work out a way of getting power from the same cable as the Raspberry Pi.

12v splitters for PoE do exist: 
![image](https://user-images.githubusercontent.com/9089056/87446083-c075f400-c5f0-11ea-9ae2-6b95c68f0400.png)

So it would be possible with two ethernet cables, but that defeats the point.

It also seems possible to power two low-power devices by splitting a PoE cable: https://networkengineering.stackexchange.com/questions/32560/multiple-poe-over-a-single-cable
![image](https://user-images.githubusercontent.com/9089056/87446819-b7d1ed80-c5f1-11ea-9b8e-d91631d2c820.png)

Which could be our best option as long as both of our PoE splitters support "Mode A" operation

**Comment by t0mhaines** [comment]
[Apparently](https://electronics.stackexchange.com/questions/271509/stepping-down-48v-from-power-over-ethernet-to-5v), PoE switches require some negotiation before they supply power. This means we can't just plug the power rails into a transformer and expect power. This means just buying the transformer as you suggested in #15 won't work.

We can either buy a [microcontroller](https://www.st.com/content/st_com/en/products/power-management/power-over-ethernet-ics/pm8805.html#sample-buy) and start building our own PCBs, or we can buy a splitter made by someone that knows what they're doing: https://www.amazon.co.uk/DSLRKIT-Active-Splitter-Ethernet-IEEE802-3at/dp/B01H37XNHE

![image](https://user-images.githubusercontent.com/194400/87527104-90c3fc00-c683-11ea-8dc1-cf6fc9ca2baf.png)

We can easily cut the plug off this and split the wire directly into our relay.

**Comment by nelsonic** [comment]
@th0mas yeah, I was thinking the same thing. (_Good detective work BTW!_)  💭 
Sadly it's not as simple as grabbing the power from the POE. 🙄  🤦 
Thankfully all the _external_ doors have a **`240v`** AC socket next to the Ethernet socket. 💡 
![ethernet-power-socket](https://user-images.githubusercontent.com/194400/87541182-c1faf700-c698-11ea-93c9-92c68ad59248.jpeg)
(_we added this "just in case" powering the doors via POE wasn't an option ..._)
So if we have to, we can always place a 12V DC power supply for each Door controlled by a relay from the RPi0.
I think it might actually be the best course of action for now as the hardware side isn't the most important part.
(_provided we can get a relay working to activate a 12V "thing" we can work out the rest later!_)

**Comment by nelsonic** [comment]
@th0mas _definitely_ continue with your current line of development 
as we will _deploy_ it @home as soon as it's working end-to-end. :shipit: 

What I'm proposing below is related to the hardware side of things, the software will not need to change.

This is probably a crazy idea, but it might work so please bare with me ... 💡 
As you have noted above, converting POE 48V to 12V for each of the **20 doors** might be a bit tedious. 💭 
(_we will do it where there is no other option, but maybe we need to think laterally on this ..._)

What if we could _sidestep_ the `POE 48V 600mA -> 12V 3A` (_power stepdown_) thing _entirely_ (_for the doors_) and just use a _single_ **12V 3A power supply** to power _all_ the Doors _directly_ using a central relay board in the server rack? 
We would still use **2 pairs** of wires in the the `CAT6` cable for the `12v 3A` to the Electric Strike 
and use the other **2 pairs** for the `UART` connecting the RPI0 to the NFC/RFID reader. 

TBC. (_requires more research_)

**Note**: ***Edit*** this comment to reveal more notes. I need to finish drawing the diagram/schematic for clarity before sharing.
<!-- 
Can we send higher current over CAT6 Cable?
https://electronics.stackexchange.com/questions/130341/current-over-cat6-ethernet-cable

https://electronics.stackexchange.com/questions/128791/maximum-cable-length-3v-uart-signals-over-ethernet
![image](https://user-images.githubusercontent.com/194400/87576735-b8d64e00-c6c9-11ea-90f8-4264f5f73eef.png)


How long can the wires connecting the RPi to the NFC/RFID reader over UART be? ❓ 
If they can be (up to) **`20m`**, then we could have the RPi in the central server cabinet powered by mains
and all the locks powered by a _single_ 12V 3A power supply. 
For this to work, we would need "hack" the CAT6 cable to be used as a data and power line instead of networking.


Max Length of USB cable: https://superuser.com/questions/64744/maximum-length-of-a-usb-cable
![image](https://user-images.githubusercontent.com/194400/87566253-a43e8980-c6ba-11ea-82dc-9ef88c540d8e.png)

I checked and our CAT6 is rated as AWG23 which means it can handle 0.729 Amps of _continuous_ current. 

According to this Q/A 2A for 10 metres is perfectly reasonable through _one_ twisted pair. 
https://electronics.stackexchange.com/questions/365167/how-much-current-run-through-my-cat6-24awg-cables

I read https://electronics.stackexchange.com/questions/31949/maximum-cable-length-for-3-3v-uart-signals/31987 but it was inconclusive. 

For a bit more context, we currently have a **16 port POE Switch** which I originally bought to power the Wifi APs.
We have a total of 20 POE ports. Which means that we will have to buy another POE Switch if we go down the POE route.

A thread to connect a `PN532` to a RPi via USB->UART Converter exists: https://github.com/nfc-tools/libnfc/issues/479
but the commenters have forgotten to update it, so it's inconclusive. 🤷 
So, for now, we are assuming that we still need one RPI per NFC/RFID reader if used over UART.

**Comment by t0mhaines** [comment]
The relay we have bought and are currently using is a 5v relay, but the Raspberry Pi's GPIO pins can only push out 3.3v

To get around this we probably need to use a Logic Converter:

![image](https://user-images.githubusercontent.com/9089056/88403567-a42e4000-cdc4-11ea-98dc-5e07ac6802e4.png)

to make sure we properly step up and step down our voltages

**Comment by t0mhaines** [comment]
This is currently how I've got the relay wired up:
![image](https://user-images.githubusercontent.com/9089056/88404448-d2604f80-cdc5-11ea-988b-9f7863388f3e.png)

**Comment by nelsonic** [comment]
@th0mas which wire is going to the PI?
This is what I was going on: https://www.instructables.com/id/5V-Relay-Raspberry-Pi

**Comment by t0mhaines** [comment]
None currently, I presumed we'd need to step up voltages but that guide suggests different.

I'll wire it up as suggested and let you know

**Comment by nelsonic** [comment]
Cool. Yeah, I was honestly under the impression that RPI Zero/3/4 have **`5v`** power at pins 2 & 4 (_top left_): https://www.raspberrypi.org/documentation/usage/gpio
![GPIO-Pinout-Diagram-2 (1)](https://user-images.githubusercontent.com/194400/88405561-5ebf4200-cdc7-11ea-9d1a-beef0bdd2caf.png)

Look forward to seeing how you get on. 👍

**Comment by t0mhaines** [comment]
Strike lock being controlled successfully and documented
